= Admin Designer Toolkit

The aim of this application is to make it easier to customize http://github.com/adminfaces/admin-theme[Admin theme^] and http://github.com/adminfaces/admin-template[Admin Template].


== What is it?

This the same http://github.com/adminfaces/admin-showcase[Admin Showcase^] application with `admin template` and `admin theme` bundled inside (https://github.com/adminfaces/admin-designer/tree/master/src/main/webapp/resources/primefaces-admin[see here^]) instead of being a project dependency.

It uses http://wildfly-swarm.io/[Wildfly Swarm^] to run the `exploded` application so one can change the theme and see the modifications without needing to restart the application.  

== Objectives

The initial idea was to speed AdminFaces development but it turns out that it can easy `contributions` from non Java developers (like designers and frontend developers) as the project is about front end components and layout.

== How it works

In application root directory:

. First start the application by running the command:
+
----
./mvnw wildfly-swarm:run (or mvnw.cmd wildfly-swarm:run)
----
+
. Second edit any less file in directory https://github.com/adminfaces/admin-designer/tree/master/src/main/resources/less[`src/main/resources/less`^].
. Finally compile the application using:
+
----
 ./mvnw compile (or mvnw.cmd compile)
----
TIP: If you don't want to compile every time you change a less file, use the flag `-Dlesscss.watch=true`.

The changes made to less files should be visible in running application `http://localhost:8080/showcase`

NOTE: There is no need to stop and run the application again.

When you are done you can get the theme in https://github.com/adminfaces/admin-designer/tree/master/src/main/webapp/resources/primefaces-admin[src/main/webapp/resources/primefaces-admin^];

You can see this workflow in the following video: https://www.youtube.com/watch?v=AGo03YqjyDM